@sharply.server_HostAddress = http://localhost:8000

### Register a new user
POST {{sharply.server_HostAddress}}/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "password"
}

### Login an existing user
POST {{sharply.server_HostAddress}}/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password"
}
